POST {{$dotenv SERVER}}/
Content-Type: application/fhir+json
Accept: application/fhir+json
Authorization: Basic {{$dotenv USER}}:{{$dotenv PASS}}

< ../synthea/output/fhir/Brendan_McCullough_6e53e49c-328c-541e-ab99-e2ba7b988a8a.json